import Head from 'next/head'
import Image from 'next/image'
import { useReducer } from 'react'
import styles from '../styles/Home.module.css'

const reducer = (state, action) => {
  switch (action.type) {
    case 'change': 
      return {
        ...state,
        [action.field]: action.payload
      }
    case 'search': 
      return {
        ...state,
        phones: action.payload.data
      }
  }
}

export default function Home({ data }) {
  const [state, dispatch] = useReducer(reducer, {
    phones: data.data.data,
    search: ''
  })

  const search = (e) => {
    dispatch({
      type: 'change',
      field: e.target.name,
      payload: e.target.value
    })
    fetch(`https://ezeapi-prod-copy.herokuapp.com/api/v1/sell-request/in-stock?sort=new&limit=20&page=1&minPrice=0&maxPrice=2500&storageSizeString=&conditionString=&category=Smartphones&brand=Apple,Samsung,Google,Huawei,LG,Motorola,OnePlus`)
    .then(res => res.json())
    .then(data => {
      if (e.target.value !== '') {
        const data1 = data.data.data.filter(item => item.name.toLowerCase().match(state.search))
        dispatch({ type: 'search', payload: { data: data1 }})
      } else if (e.target.value == ''){
        dispatch({ type: 'search', payload: { data: data.data.data }})
      }
    })
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>IphoneHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.head}>Phones Hub</h1>
      
      <div className={styles.inputDiv}>
        <input 
          type='text' 
          name='search' 
          id='search' 
          value={state.search}
          placeholder='Search for your favorite phones'
          style={{backgroundColor: 'transparent', padding: '0.7rem 1rem', border: '0.2px solid grey', outline: 'none', minHeight: '30px', width: '100%'}}
          onChange={(e) => search(e)}
        />
      </div>

      <div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'center'}}>
        {
          state.phones.map((item, index) => 
            <Card image={item.imgUrl} name={item.name} storage={item.lowestAsk?.storageSize} grade={item.lowestAsk?.grade} key={index}/>  
          )
        }
      </div>
    </div>
  )
}

const Card = ({image, name, storage, grade}) => {
  return (
    <div style={{width: '350px', display: 'flex', backgroundColor: '#ffffff', margin: '10px', padding: '2rem 2rem 2rem 0', boxShadow: '2px 3px 9px 1px black'}}>
      <div>
        <Image src={image} width={195} height={195} />
      </div>
      <div style={{display: 'flex', flexDirection: 'column', justifyContent: 'flex-end'}}>
        <div style={{maxWidth: '170px', paddingBottom: '.9rem'}}>
          <h3 style={{textDecoration: 'capitalize', marginBottom: '0'}}>{name}</h3>
          <div>
            <div>Storage: {storage}</div>
            <div>Grade: {grade}</div>
          </div>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://ezeapi-prod-copy.herokuapp.com/api/v1/sell-request/in-stock?sort=new&limit=20&page=1&minPrice=0&maxPrice=2500&storageSizeString=&conditionString=&category=Smartphones&brand=Apple,Samsung,Google,Huawei,LG,Motorola,OnePlus')
  const data = await res.json()

  return {
    props: { 
      data
    }
  }
}